# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bizzy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bizzy
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
#Apple Authentication UI
pod 'FirebaseUI/OAuth'
pod 'AlamofireImage'
pod 'Moya'
pod 'SwiftLocation', '~> 4.0'

end
